version: '3.3'
services:
  db:
    container_name: db
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    env_file:
      - ./.env

  backend:
    container_name: backend
    image: blackford/foodgram_backend:latest
    restart: always
    volumes:
      - static_value:/backend/static/
      - media_value:/backend/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: blackford/foodgram_front:latest
    volumes:
      - ../frontend/:/app/result_build/
      - static_value:/var/html/static/
    volumes:
      - ../frontend/:/app/result_build/
    restart: always
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - static_value:/static/
      - media_value:/media/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - frontend

volumes:
  postgres_data:
  static_value:
  media_value:
